#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Run startup-oriented MSRR simulations using shared core Modelica files."""

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

try:
    from .paths import default_startup_run_dir, startup_result_prefix
except ImportError:
    from paths import default_startup_run_dir, startup_result_prefix


CORE_MODEL_TO_SCENARIO_MODEL = {
    "startup": {
        "1r": "MSRR.MSRRstartUpCriticality",
        "9r": "MSRR.MSRRstartUpCriticality9R",
    },
    "startup_to_100kw": {
        "1r": "MSRR.MSRRstartUpTo100kW",
        "9r": "MSRR.MSRRstartUpTo100kW9R",
    },
    "startup_to_1mw": {
        "1r": "MSRR.MSRRstartUpTo1MW",
        "9r": "MSRR.MSRRstartUpTo1MW9R",
    },
}

SCENARIOS = {
    "startup": {
        "stop_time": 108000.0,
        "number_of_intervals": 1080000,
    },
    "startup_to_100kw": {
        "stop_time": 151200.0,
        "number_of_intervals": 151200,
    },
    "startup_to_1mw": {
        "stop_time": 151200.0,
        "number_of_intervals": 151200,
    },
}


def parse_args() -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[1]
    default_core_dir = str(repo_root / "core")

    parser = argparse.ArgumentParser(description="Run MSRR startup simulation.")
    parser.add_argument(
        "--run_dir",
        type=str,
        default=None,
        help=(
            "Directory where run artifacts/logs/results are written "
            "(default: 00runs/startup-<scenario>-<core_model>)"
        ),
    )
    parser.add_argument(
        "--core_dir",
        type=str,
        default=default_core_dir,
        help="Directory containing core Modelica files (default: ../core)",
    )
    parser.add_argument(
        "--library_file",
        type=str,
        default="SMD_MSR_Modelica.mo",
        help="Core Modelica library filename",
    )
    parser.add_argument(
        "--model_file",
        type=str,
        default="MSRR.mo",
        help="Core MSRR model filename",
    )
    parser.add_argument(
        "--core_model",
        type=str,
        choices=("1r", "9r"),
        default="1r",
        help="Core segmentation to use: 1r or 9r",
    )
    parser.add_argument(
        "--scenario",
        type=str,
        choices=sorted(SCENARIOS.keys()),
        default="startup",
        help="Predefined startup run configuration",
    )
    parser.add_argument(
        "--model_name",
        type=str,
        default=None,
        help="Modelica model to simulate (overrides --scenario/--core_model mapping)",
    )
    parser.add_argument("--start_time", type=float, default=0.0, help="Simulation start time (s)")
    parser.add_argument(
        "--stop_time",
        type=float,
        default=None,
        help="Simulation stop time (s). Default depends on scenario.",
    )
    parser.add_argument(
        "--number_of_intervals",
        type=int,
        default=None,
        help="Number of output intervals. Default depends on scenario.",
    )
    parser.add_argument("--tolerance", type=float, default=1e-6, help="Solver relative tolerance")
    parser.add_argument("--method", type=str, default="dassl", help="DAE solver method")
    parser.add_argument("--output_format", type=str, default="csv", help="Output format")
    parser.add_argument(
        "--file_prefix",
        type=str,
        default=None,
        help="Result file prefix (defaults by scenario/core_model)",
    )
    parser.add_argument("--max_step_size", type=float, default=0.01, help="Maximum solver step size")
    parser.add_argument("--extra_simflags", type=str, default="", help="Additional simflags")
    parser.add_argument(
        "--mos_name",
        type=str,
        default="runMSRR_generated.mos",
        help="Generated .mos script filename",
    )
    parser.add_argument("--keep_mos", action="store_true", help="Keep generated .mos script after run")
    parser.add_argument("--omc", type=str, default="omc", help="OpenModelica compiler command")
    return parser.parse_args()


def build_simflags(max_step_size: float, extra_simflags: str) -> str:
    simflags = f"-maxStepSize={max_step_size:.10g}"
    extra = extra_simflags.strip()
    if extra:
        simflags = f"{simflags} {extra}"
    return simflags


def build_mos_text(
    library_path: str,
    model_path: str,
    resolved_model_name: str,
    start_time: float,
    resolved_stop_time: float,
    resolved_number_of_intervals: int,
    tolerance: float,
    method: str,
    output_format: str,
    resolved_file_prefix: str,
    simflags: str,
) -> str:
    return (
        "// Generated by startup/runMSRR.py\n"
        f'loadFile("{library_path}");\n'
        f'loadFile("{model_path}");\n'
        f"simulate({resolved_model_name},"
        f"startTime={start_time:.10g},"
        f"stopTime={resolved_stop_time:.10g},"
        f"numberOfIntervals={resolved_number_of_intervals},"
        f"tolerance={tolerance:.10g},"
        f"method={method},"
        f'outputFormat="{output_format}",'
        f'fileNamePrefix="{resolved_file_prefix}",'
        f'simflags="{simflags}");\n'
    )


def main() -> int:
    args = parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    if args.run_dir is None:
        run_dir = str(
            default_startup_run_dir(
                repo_root,
                scenario=args.scenario,
                core_model=args.core_model,
            )
        )
    else:
        run_dir = os.path.abspath(args.run_dir)
    core_dir = os.path.abspath(args.core_dir)
    library_path = os.path.join(core_dir, args.library_file)
    model_path = os.path.join(core_dir, args.model_file)

    try:
        os.makedirs(run_dir, exist_ok=True)
    except OSError as exc:
        print(f"ERROR: unable to create run directory: {run_dir}")
        print(f"  {exc}")
        return 2
    if not os.path.isdir(run_dir):
        print(f"ERROR: run path is not a directory: {run_dir}")
        return 2
    if not os.path.isdir(core_dir):
        print(f"ERROR: core directory does not exist: {core_dir}")
        return 2
    if not os.path.exists(library_path):
        print(f"ERROR: missing library file: {library_path}")
        return 2
    if not os.path.exists(model_path):
        print(f"ERROR: missing model file: {model_path}")
        return 2

    scenario_defaults = SCENARIOS[args.scenario]
    resolved_model_name = args.model_name
    if resolved_model_name is None:
        resolved_model_name = CORE_MODEL_TO_SCENARIO_MODEL[args.scenario][args.core_model]
    if "nominaltrim" in resolved_model_name.lower():
        print(
            "ERROR: startup/runMSRR.py expects startup models. "
            f"Got nominal-trim model: {resolved_model_name}"
        )
        return 2
    resolved_file_prefix = args.file_prefix
    if resolved_file_prefix is None:
        resolved_file_prefix = startup_result_prefix(
            scenario=args.scenario,
            core_model=args.core_model,
        )
    resolved_stop_time = (
        args.stop_time if args.stop_time is not None else scenario_defaults["stop_time"]
    )
    resolved_number_of_intervals = (
        args.number_of_intervals
        if args.number_of_intervals is not None
        else scenario_defaults["number_of_intervals"]
    )

    mos_path = os.path.join(run_dir, args.mos_name)
    result_csv = os.path.join(run_dir, f"{resolved_file_prefix}_res.csv")
    simflags = build_simflags(args.max_step_size, args.extra_simflags)

    try:
        if os.path.exists(result_csv):
            os.remove(result_csv)
    except OSError:
        pass

    with open(mos_path, "w") as handle:
        handle.write(
            build_mos_text(
                library_path=library_path,
                model_path=model_path,
                resolved_model_name=resolved_model_name,
                start_time=args.start_time,
                resolved_stop_time=resolved_stop_time,
                resolved_number_of_intervals=resolved_number_of_intervals,
                tolerance=args.tolerance,
                method=args.method,
                output_format=args.output_format,
                resolved_file_prefix=resolved_file_prefix,
                simflags=simflags,
            )
        )

    print("Running MSRR startup simulation")
    print(f"  Run dir:            {run_dir}")
    print(f"  Core dir:           {core_dir}")
    print(f"  Core model:         {args.core_model}")
    print(f"  Scenario:           {args.scenario}")
    print(f"  Model:              {resolved_model_name}")
    print(f"  Start/stop:         {args.start_time} -> {resolved_stop_time} s")
    print(f"  Intervals:          {resolved_number_of_intervals}")
    print(f"  Tolerance:          {args.tolerance}")
    print(f"  Method:             {args.method}")
    print(f"  Output format:      {args.output_format}")
    print(f"  File prefix:        {resolved_file_prefix}")
    print(f"  Simflags:           {simflags}")
    print(f"  OMC script:         {mos_path}")
    print("=" * 72)

    result = subprocess.run(
        [args.omc, "--showErrorMessages", args.mos_name],
        cwd=run_dir,
        capture_output=True,
        text=True,
    )

    stdout_log = os.path.join(run_dir, "runMSRR_py_omc_stdout.log")
    stderr_log = os.path.join(run_dir, "runMSRR_py_omc_stderr.log")
    with open(stdout_log, "w") as handle:
        handle.write(result.stdout)
    with open(stderr_log, "w") as handle:
        handle.write(result.stderr)

    if not args.keep_mos:
        try:
            os.remove(mos_path)
        except OSError:
            pass

    if result.returncode != 0:
        print(f"ERROR: omc failed with exit code {result.returncode}")
        print(f"  Stdout log: {stdout_log}")
        print(f"  Stderr log: {stderr_log}")
        return result.returncode

    combined_output = f"{result.stdout}\n{result.stderr}"
    failed_in_record = "Simulation execution failed for model" in combined_output
    empty_result_file = bool(re.search(r'resultFile\s*=\s*""', combined_output))

    if failed_in_record or empty_result_file:
        print("ERROR: OpenModelica reported simulation failure.")
        print(f"  Stdout log: {stdout_log}")
        print(f"  Stderr log: {stderr_log}")
        return 4

    if not os.path.exists(result_csv):
        print("ERROR: omc exited successfully but result CSV is missing.")
        print(f"  Expected: {result_csv}")
        print(f"  Stdout log: {stdout_log}")
        print(f"  Stderr log: {stderr_log}")
        return 3

    print("Simulation completed successfully.")
    print(f"  Result CSV:  {result_csv}")
    print(f"  Stdout log:  {stdout_log}")
    print(f"  Stderr log:  {stderr_log}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
